## EVALUACIÓN 3: MODULO 2, SPRINT 1

### Ejercicios de NumPy

1- Importa la librería de NumPy. ✅

In [5]:
import numpy as np

2- Crea un array de 1 dimension y 10 elementos.

In [6]:
# utilizamos el metodo de numpy random.randint para crear un array aleatorio de numeros enteros (0-100)
mi_array = np.random.randint(0,100, (10))
mi_array

array([79,  4, 83, 42, 15, 61, 37, 86,  1, 93])

3- Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [7]:
# creamos una función que remplace los números por el texto deseado
def par_impar(array):
    '''
    Función que combierte un array numérico a otro del mismo tamaño donde los números
    se intercambian por strings que indican si dicho número era par o impar.

    Parametro: la función necesita un array numérico
    Return: devuelve un array con strings 'par' o 'impar' en función del parámetro dado
    '''
    
    lista_texto = []
    for a in array:
        if a % 2 == 0:
            lista_texto.append('par')
        else:
            lista_texto.append('impar')
    array_texto = np.array(lista_texto)
    return array_texto

In [8]:
array_resultado = par_impar(mi_array)
array_resultado

array(['impar', 'par', 'impar', 'par', 'impar', 'impar', 'impar', 'par',
       'impar', 'impar'], dtype='<U5')

4- Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [9]:
# utilizamos el método .reshape() de numpy
array_cambiado = array_resultado.reshape(2,5)
array_cambiado

array([['impar', 'par', 'impar', 'par', 'impar'],
       ['impar', 'impar', 'par', 'impar', 'impar']], dtype='<U5')

5- Extrae los elementos comunes de los siguientes arrays

In [10]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [11]:
# utilizamos el método .intersect1d() para encontrar los elementos comunes
np.intersect1d(array1, array2)

array([2, 4])

6- Extraed los elementos que están en el array1 pero no en el array2.

In [12]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7- Extraed las posiciones donde tengamos elementos que sean iguales.

In [13]:
posiciones = np.intersect1d(array1, array2, return_indices=True)[1:]
posiciones

(array([1, 5]), array([1, 5]))

8- Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [14]:
mi_array2 = np.random.randint(0,50, (3,5))
mi_array2

array([[ 5, 25, 17, 46, 34],
       [ 8, 10, 25, 21,  8],
       [ 0, 29, 29, 49, 25]])

In [15]:
def diez_cuarenta(array):
    '''
    Función que coje un array bidimensional y devuelve en una lista los valores
    menores de 10 y mayores de 40.

    Parámetro: un array bidimensional
    Return: devuelve una lista con los numeros que cumplen las condiciones dadas
    '''
    lista_numeros= []
    for a in mi_array2:
        for n in a:
            if n < 10:
                lista_numeros.append(n)
            elif n > 40:
                lista_numeros.append(n)
            else:
                pass
    return lista_numeros

In [16]:
array1040 = diez_cuarenta(mi_array2)
array1040

[5, 46, 8, 8, 0, 49]

9- Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [17]:
# existe la funcion de numpy random.uniform(), similar a random.randint() pero para numeros decimales
mi_array3 = np.random.uniform(5,10, (10))
mi_array3

array([7.18806836, 8.3688788 , 9.06740822, 5.43776262, 5.82198294,
       5.88533699, 9.00477298, 9.76710951, 5.7174254 , 8.85537722])

10- Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [18]:
mi_array4 = np.random.randint(0,9,(2,4,7))
mi_array4

array([[[2, 3, 6, 3, 3, 8, 2],
        [8, 5, 2, 8, 0, 0, 2],
        [7, 1, 3, 4, 8, 7, 5],
        [1, 4, 5, 4, 5, 6, 3]],

       [[4, 7, 6, 6, 2, 6, 1],
        [5, 1, 7, 0, 1, 4, 1],
        [4, 2, 4, 0, 7, 0, 0],
        [8, 1, 7, 8, 0, 4, 0]]])

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [19]:
array_cambiado = np.transpose(mi_array4, (1,2,0))
array_cambiado

array([[[2, 4],
        [3, 7],
        [6, 6],
        [3, 6],
        [3, 2],
        [8, 6],
        [2, 1]],

       [[8, 5],
        [5, 1],
        [2, 7],
        [8, 0],
        [0, 1],
        [0, 4],
        [2, 1]],

       [[7, 4],
        [1, 2],
        [3, 4],
        [4, 0],
        [8, 7],
        [7, 0],
        [5, 0]],

       [[1, 8],
        [4, 1],
        [5, 7],
        [4, 8],
        [5, 0],
        [6, 4],
        [3, 0]]])