## EVALUACIÓN 3: MODULO 2, SPRINT 1

### Ejercicios de NumPy

1- Importa la librería de NumPy. ✅

In [1]:
import numpy as np

2- Crea un array de 1 dimension y 10 elementos.

In [2]:
# utilizamos el metodo de numpy random.randint para crear un array aleatorio de numeros enteros (0-100)
mi_array = np.random.randint(0,100, (10))
mi_array

array([71, 78, 42, 89, 56, 19, 52, 68, 77, 90])

3- Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [13]:
# creamos una función que remplace los números por el texto deseado
def par_impar(array):
    '''
    Función que combierte un array numérico a otro del mismo tamaño donde los números
    se intercambian por strings que indican si dicho número era par o impar.

    Parametro: la función necesita un array numérico
    Return: devuelve un array con strings 'par' o 'impar' en función del parámetro dado
    '''
    
    lista_texto = []
    for a in array:
        if a % 2 == 0:
            lista_texto.append('par')
        else:
            lista_texto.append('impar')
    array_texto = np.array(lista_texto)
    return array_texto

In [14]:
array_resultado = par_impar(mi_array)
array_resultado

array(['impar', 'par', 'par', 'impar', 'par', 'impar', 'par', 'par',
       'impar', 'par'], dtype='<U5')

4- Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [9]:
# utilizamos el método .reshape() de numpy
array_cambiado = array_resultado.reshape(2,5)
array_cambiado

array([['impar', 'par', 'impar', 'par', 'impar'],
       ['impar', 'impar', 'par', 'impar', 'impar']], dtype='<U5')

5- Extrae los elementos comunes de los siguientes arrays

In [22]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [23]:
# utilizamos el método .intersect1d() para encontrar los elementos comunes
np.intersect1d(array1, array2)

array([2, 4])

6- Extraed los elementos que están en el array1 pero no en el array2.

In [24]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7- Extraed las posiciones donde tengamos elementos que sean iguales.

In [32]:
# no tiene en cuenta valores repetidos
posiciones = np.intersect1d(array1, array2, return_indices=True)[1:]
posiciones

(array([1, 5]), array([1, 5]))

In [29]:
# posiciones del array1 contando numeros repetidos
np.where(array1 == array2)

(array([1, 3, 5, 7]),)

In [31]:
# posiciones del array1 contando números repetidos
np.where(array2 == array1)

(array([1, 3, 5, 7]),)

8- Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [35]:
mi_array2 = np.random.randint(0,50, (3,5))
mi_array2

array([[24, 25, 38, 34, 14],
       [ 8, 11, 38, 21, 15],
       [36, 47,  2, 43,  1]])

In [36]:
def diez_cuarenta(array):
    '''
    Función que coje un array bidimensional y devuelve en una lista los valores
    menores de 10 y mayores de 40.

    Parámetro: un array bidimensional
    Return: devuelve una lista con los numeros que cumplen las condiciones dadas
    '''
    lista_numeros= []
    for a in mi_array2:
        for n in a:
            if n < 10:
                lista_numeros.append(n)
            elif n > 40:
                lista_numeros.append(n)
            else:
                pass
    return lista_numeros

In [37]:
array1040 = diez_cuarenta(mi_array2)
array1040

[8, 47, 2, 43, 1]

9- Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [38]:
# existe la funcion de numpy random.uniform(), similar a random.randint() pero para numeros decimales
mi_array3 = np.random.uniform(5,10, (10))
mi_array3

array([5.95142841, 9.60697249, 9.460464  , 9.04167909, 8.92225289,
       6.21188347, 6.28451861, 5.71922159, 6.45873134, 7.59009074])

10- Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [40]:
mi_array4 = np.random.randint(1,20,(2,4,7))
mi_array4

array([[[ 1,  8, 12, 14,  8,  9, 16],
        [14, 13,  6, 18, 15,  1,  3],
        [18, 14, 18,  6, 16,  2,  1],
        [ 6,  2, 16, 15, 13, 12,  9]],

       [[16, 19, 13, 10, 10,  1,  8],
        [11,  2,  7,  9,  2, 14, 14],
        [ 5, 19, 16, 11,  6,  2, 15],
        [ 7,  7,  2,  8, 18,  5,  2]]])

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [41]:
array_cambiado = np.transpose(mi_array4, (1,2,0))
array_cambiado

array([[[ 1, 16],
        [ 8, 19],
        [12, 13],
        [14, 10],
        [ 8, 10],
        [ 9,  1],
        [16,  8]],

       [[14, 11],
        [13,  2],
        [ 6,  7],
        [18,  9],
        [15,  2],
        [ 1, 14],
        [ 3, 14]],

       [[18,  5],
        [14, 19],
        [18, 16],
        [ 6, 11],
        [16,  6],
        [ 2,  2],
        [ 1, 15]],

       [[ 6,  7],
        [ 2,  7],
        [16,  2],
        [15,  8],
        [13, 18],
        [12,  5],
        [ 9,  2]]])